services:
  sokoke_planner_api-production:
    container_name: sokoke_planner_api-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-3001}
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4096m'
        reservations:
          cpus: '0.25'
          memory: '2048m'

  sokoke_planner_api-dev:
    container_name: sokoke_planner_api-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3001}
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
      - '9228:9228'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    volumes:
      - .:/project
      - node_modules:/project/node_modules/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4096m'
        reservations:
          cpus: '0.25'
          memory: '2048m'

volumes:
  node_modules:
