services:
  sokoke_planner_api-production:
    container_name: sokoke_planner_api-production
    build:
      target: prod
      context: .
      args:
        - PORT=${PORT:-4003}
    ports:
      - '${PORT:-4003}:${PORT:-4003}'
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4096m'
        reservations:
          cpus: '0.25'
          memory: '2048m'
    profiles: ["prod"]

  sokoke_planner_api-dev:
    container_name: sokoke_planner_api-dev
    restart: unless-stopped
    env_file: .env-docker
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-4003}
    ports:
      - '${PORT:-4003}:${PORT:-4003}'
      - '9229:9229'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
      - CHOKIDAR_USEPOLLING=true
      - MONGODB_URI=mongodb://host.docker.internal:27017/sokokePlanner
    volumes:
      - .:/project
      - node_modules:/project/node_modules/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4096m'
        reservations:
          cpus: '0.25'
          memory: '2048m'
    profiles: ["dev"]

volumes:
  node_modules:
